trigger:
  batch: 'true'
  branches:
    include:
    - main
  paths:
    exclude:
      - README.md
      - LICENSE.txt
      - .gitignore
      - .dockerignore

resources:
- repo: self

stages:
- stage: Build_CMS_Image
  displayName: Build CMS image
  jobs:
  - job: Build_CMS_Image
    displayName: Build CMS image
    pool:
      name: Redshift-OnPrem-Linux
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Building CMS Image
      inputs:
        command: buildAndPush
        containerRegistry: 'DockerHub-awesomejack295'
        repository: 'awesomejack295/mediacms'
        dockerfile: './Dockerfile'
        tags: latest
    - task: CmdLine@2
      displayName: Cleaning up images older than 24H
      inputs:
       script: 'docker system prune -a --force --filter "until=24h"' 

    - task: CmdLine@2
      displayName: Cleaning up unneeded images
      inputs:
       script: 'docker system prune -f'